name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: prime-cache-235f36d
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/my-dependencies   # change this to your actual dependencies folder if needed
          key: cache-235f36d

      - name: Show cache result
        run: echo "Cache hit: ${{ steps.cache-step.outputs.cache-hit }}"

      - name: 23f2000091@ds.study.iitm.ac.in
        run: echo Hello, world!
      
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
