name: Cache dependencies

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cache-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: prime-cache-235f36d
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/my-dependencies
          key: cache-235f36d

      - name: Show cache result
        run: echo "Cache hit: ${{ steps.cache-step.outputs.cache-hit }}"
